config/routes.rb
Rails.application.routes.draw do
  resources :games do
    resources :moves, only: [:create]
  end

  root to: 'games#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
    before_validation(on: :create) do
      self.state = {
        0 => { 0 => nil, 1 => nil, 2 => nil },
        1 => { 0 => nil, 1 => nil, 2 => nil },
        2 => { 0 => nil, 1 => nil, 2 => nil },
      }
      self.current_symbol = [:x, :o].sample
    end
  
    after_update_commit { broadcast_update }
  
    def [](row, col)
      state[row.to_s][col.to_s]
    end
  
    # 0, 0
    def move!(row, col)
      state[row.to_s][col.to_s] = current_symbol
  
      # swap current symbol
      self.current_symbol = current_symbol == "x" ? "o" : "x"
      self.save!
    end

    def checkwinner
        row_winner = checkArrForWinner(rowToArr)
        col_winner = checkArrForWinner(colToArr)
        diagonal_winner = checkArrForWinner(diagonalsToArr)

        #Check horizontal combinations
        return row_winner unless row_winner.nil?
        #Check vertical combinations
        return col_winner unless col_winner.nil?
        #Check diagonal combinations
        return diagonal_winner unless diagonal_winner.nil?
        

        return nil
    end
    
    def checkArrForWinner(arr)
        arr.each do |n|
            if n.uniq.size <= 1 && n[0] != nil
                return n[0]
            end
        end
        return nil
    end


    def rowToArr
        new_arr = [[],[],[]]

        3.times do |r|
            3.times do |c|
                new_arr[r] << state[r.to_s][c.to_s]
            end
        end
        new_arr
    end

    def colToArr
        new_arr = [[], [], []]

        3.times do |r|
            3.times do |c|
                new_arr[r] << state[c.to_s][r.to_s]
            end
        end
        new_arr
    end

    def diagonalsToArr
        new_arr = [[], []]
        aux_index = 2

        2.times do |r|
            3.times do |c|
                if aux_index >= 0
                    new_arr[r] << state[c.to_s][aux_index.to_s]
                    aux_index -= 1
               else
                    new_arr[r] << state[c.to_s][c.to_s]
               end
            end
        end
        new_arr
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
    @winner = @game.checkwinner
  end

  def create
    redirect_to Game.create
  end
end

app/controllers/moves_controller.rb
class MovesController < ApplicationController
    def create
        @game = Game.find(params[:game_id])
        @game.move!(params[:row], params[:col])
        @winner = @game.checkwinner

        respond_to do |format|
          format.turbo_stream
          format.html {
            redirect_to @game
          }
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/moves_helper.rb
module MovesHelper
end

app/views/games/_game.html.erb
<% 3.times do |row| %>
  <div class="row">
    <% 3.times do |col| %>
      <span class="cell">
        <% if !game[row, col].nil? %>
          <%= game[row, col] %>
        <% elsif @winner %>
            <%= " " %>
        <% else %>
          <%= button_to game.current_symbol, game_moves_path(game), params: { row: row, col: col }, method: :post, class: 'button_placeholder' %>
        <% end %>
      </span>
    <% end %>
  </div>
<% end %>

<p>Share this url to play with a friend: <span> <%= "http://localhost:3000/games/#{game.id}" %> </span><p>

<% if @winner %>
    <h2>The winner is <%= @winner %></h2>
    <form action="/games" method="post">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="submit" value="New game">
    </form>
<% end %>

app/views/games/index.html.erb
<h1>Games</h1>

<form action="/games" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="submit" value="New game">
</form>

app/views/games/show.html.erb
<h1>Games</h1>

<%= turbo_stream_from @game %>

<div id="<%= dom_id(@game) %>">
  <%= render @game %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TicTacToeTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/moves/create.turbo_stream.erb
<%= turbo_stream.update dom_id(@game) do %>
  <%= render @game %>
<% end %>